[package]
name = "proget-sdk"
version = "0.1.0"
authors = ["Hunter Wittenborn <hunter@hunterwittenborn.com>"]
description = "An unofficial Rust SDK for ProGet"
edition = "2021"
repository = "https://github.com/hwittenborn/proget-rust-sdk"
license = "GPL-3.0-only WITH GPL-3.0-linking-exception"
keywords = ["proget"]
categories = ["api-bindings"]

[lib]
name = "proget_sdk"

[dependencies]
url = "2.3.1"
reqwest = "0.11.12"
