name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Import Vault secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.hunterwittenborn.com
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/ci crates_api_key | CARGO_REGISTRY_TOKEN
      - name: Setup Prebuilt-MPR APT repository
        uses: makedeb/setup-makedeb@main
        with:
          makedeb-repo: false
          pbmpr-repo: true
      - name: Install Rust toolchain
        run: sudo apt-get install rustup -y
      - name: Setup default Rust toolchain
        run: rustup default stable
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Release to crates.io
        run: cargo publish
